/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectcinema;

import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import projectcinema.Logica.LogicaCinema;
import projectcinema.Logica.LogicaTicketsMenu;

/**
 *
 * @author Sofi
 */
public class SelectMovie extends javax.swing.JFrame {
    
    String lblMovieType;
    String MovieLang;
    String MovieTime;
    String Location;
    public String MovieName;
    LogicaCinema cinema = new LogicaCinema();

    /** Creates new form SelectMovie */
    public SelectMovie() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMovieLang = new javax.swing.ButtonGroup();
        buttonGroupMovieType = new javax.swing.ButtonGroup();
        buttonGroupTime = new javax.swing.ButtonGroup();
        lblSelectMovie = new javax.swing.JLabel();
        cmbMovies = new javax.swing.JComboBox<>();
        lblSchedule = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        rbtnSub = new javax.swing.JRadioButton();
        rbtnDob = new javax.swing.JRadioButton();
        btnExitSelectMovie = new javax.swing.JButton();
        btnContinueSelectMovie = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpSinopsis = new javax.swing.JTextPane();
        lblMoviePic = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        btnVIP = new javax.swing.JRadioButton();
        btn3D = new javax.swing.JRadioButton();
        btn2D = new javax.swing.JRadioButton();
        btnMoring = new javax.swing.JRadioButton();
        btnAfternoon = new javax.swing.JRadioButton();
        btnNight = new javax.swing.JRadioButton();
        btnSanP = new javax.swing.JRadioButton();
        btnPMayor = new javax.swing.JRadioButton();
        btnMEscazu = new javax.swing.JRadioButton();
        btnPFlores = new javax.swing.JRadioButton();
        lblWallpaperMovies = new javax.swing.JLabel();
        txtMovieT = new javax.swing.JTextField();
        lblUserBill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelectMovie.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblSelectMovie.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectMovie.setText("Seleccione la pelicula");
        getContentPane().add(lblSelectMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        cmbMovies.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        cmbMovies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Spiderman", "IronMan", "Batman" }));
        cmbMovies.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMoviesItemStateChanged(evt);
            }
        });
        cmbMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMoviesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 240, -1));

        lblSchedule.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lblSchedule.setText("Seleccione el Horario");
        getContentPane().add(lblSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        lblRoom.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblRoom.setForeground(new java.awt.Color(255, 255, 255));
        lblRoom.setText("Seleccione la Sala");
        getContentPane().add(lblRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        lblLocation.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Localidad");
        getContentPane().add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        groupMovieLang.add(rbtnSub);
        rbtnSub.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        rbtnSub.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSub.setText("Subtitulada");
        rbtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSubActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        groupMovieLang.add(rbtnDob);
        rbtnDob.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        rbtnDob.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDob.setText("Doblada");
        rbtnDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDobActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, -1, -1));

        btnExitSelectMovie.setFont(new java.awt.Font("Hobo Std", 1, 12)); // NOI18N
        btnExitSelectMovie.setText("SALIR");
        btnExitSelectMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSelectMovieActionPerformed(evt);
            }
        });
        getContentPane().add(btnExitSelectMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, -1, -1));

        btnContinueSelectMovie.setFont(new java.awt.Font("Hobo Std", 1, 12)); // NOI18N
        btnContinueSelectMovie.setText("CONTINUAR");
        btnContinueSelectMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueSelectMovieActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinueSelectMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, -1, -1));

        jScrollPane3.setViewportView(txtpSinopsis);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 460, 160));

        lblMoviePic.setText("jLabel1");
        getContentPane().add(lblMoviePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 370, 400));

        lblRoomType.setFont(new java.awt.Font("Hobo Std", 0, 12)); // NOI18N
        lblRoomType.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 520, 40));

        buttonGroupMovieType.add(btnVIP);
        btnVIP.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btnVIP.setForeground(new java.awt.Color(255, 255, 255));
        btnVIP.setText("VIP");
        btnVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIPActionPerformed(evt);
            }
        });
        getContentPane().add(btnVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        buttonGroupMovieType.add(btn3D);
        btn3D.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn3D.setForeground(new java.awt.Color(255, 255, 255));
        btn3D.setText("3D");
        btn3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3DActionPerformed(evt);
            }
        });
        getContentPane().add(btn3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        buttonGroupMovieType.add(btn2D);
        btn2D.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        btn2D.setForeground(new java.awt.Color(255, 255, 255));
        btn2D.setText("2D");
        btn2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2DActionPerformed(evt);
            }
        });
        getContentPane().add(btn2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, -1, -1));

        buttonGroupTime.add(btnMoring);
        btnMoring.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnMoring.setForeground(new java.awt.Color(255, 255, 255));
        btnMoring.setText("Mañana");
        btnMoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoringActionPerformed(evt);
            }
        });
        getContentPane().add(btnMoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        buttonGroupTime.add(btnAfternoon);
        btnAfternoon.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnAfternoon.setForeground(new java.awt.Color(255, 255, 255));
        btnAfternoon.setText("Tarde");
        btnAfternoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfternoonActionPerformed(evt);
            }
        });
        getContentPane().add(btnAfternoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        buttonGroupTime.add(btnNight);
        btnNight.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnNight.setForeground(new java.awt.Color(255, 255, 255));
        btnNight.setText("Noche");
        btnNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNightActionPerformed(evt);
            }
        });
        getContentPane().add(btnNight, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        btnSanP.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnSanP.setForeground(new java.awt.Color(255, 255, 255));
        btnSanP.setText("San Pedro");
        btnSanP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPActionPerformed(evt);
            }
        });
        getContentPane().add(btnSanP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        btnPMayor.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnPMayor.setForeground(new java.awt.Color(255, 255, 255));
        btnPMayor.setText("Plaza Mayor");
        btnPMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMayorActionPerformed(evt);
            }
        });
        getContentPane().add(btnPMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        btnMEscazu.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnMEscazu.setForeground(new java.awt.Color(255, 255, 255));
        btnMEscazu.setText("Multiplaza Escazu");
        btnMEscazu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEscazuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMEscazu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        btnPFlores.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        btnPFlores.setForeground(new java.awt.Color(255, 255, 255));
        btnPFlores.setText("Paseo de las Flores");
        btnPFlores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPFloresActionPerformed(evt);
            }
        });
        getContentPane().add(btnPFlores, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        lblWallpaperMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginPics/WallpaperCinema2.jpg"))); // NOI18N
        lblWallpaperMovies.setText("jLabel1");
        getContentPane().add(lblWallpaperMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1921, -1));

        txtMovieT.setText("jTextField1");
        getContentPane().add(txtMovieT, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));
        getContentPane().add(lblUserBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitSelectMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSelectMovieActionPerformed
        Login window = new Login();
        window.show();
        this.dispose();
    }//GEN-LAST:event_btnExitSelectMovieActionPerformed

    private void btnContinueSelectMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueSelectMovieActionPerformed
        TicketsMenu2 obj = new TicketsMenu2();
        obj.setVisible(true);
        TicketsMenu2.lblMovieType.setText(lblMovieType);
        TicketsMenu2.lbltestLang.setText(MovieLang);
        TicketsMenu2.lblTime1.setText(MovieTime);
        TicketsMenu2.lblLocation.setText(Location);
        
        //Bill oj2 = new Bill();
        //oj2.setVisible(true);
        //Bill.lblMovieLang.setText(MovieLang);
        
        
        //LogicaTicketsMenu log = new LogicaTicketsMenu();
        //log.back();
    }//GEN-LAST:event_btnContinueSelectMovieActionPerformed

    private void cmbMoviesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMoviesItemStateChanged
        
        LogicaCinema logica = new LogicaCinema();
        String sinopsis = logica.Movie(cmbMovies.getSelectedIndex());
        txtpSinopsis.setText(sinopsis);
        ImageIcon option = logica.Picture(cmbMovies.getSelectedIndex());
        lblMoviePic.setIcon(option); 
           
        
    }//GEN-LAST:event_cmbMoviesItemStateChanged

    private void cmbMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMoviesActionPerformed
        
    }//GEN-LAST:event_cmbMoviesActionPerformed

    private void btnVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIPActionPerformed
        TicketsMenu2 type = new TicketsMenu2();
        LogicaCinema logica = new LogicaCinema();
        String roomType = logica.vip();
        lblRoomType.setText(roomType);
        lblMovieType= "VIP";
        
    }//GEN-LAST:event_btnVIPActionPerformed

    private void btn3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3DActionPerformed
        LogicaCinema logica = new LogicaCinema();
        String roomType = logica.trdD();
        lblRoomType.setText(roomType);
        lblMovieType= "3D";
    }//GEN-LAST:event_btn3DActionPerformed

    private void btn2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2DActionPerformed
        LogicaCinema logica = new LogicaCinema();
        String roomType = logica.sndD();
        lblRoomType.setText(roomType);
        lblMovieType= "2D";
    }//GEN-LAST:event_btn2DActionPerformed

    private void rbtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSubActionPerformed
        
        MovieLang = "Subtitulada";
    }//GEN-LAST:event_rbtnSubActionPerformed

    private void rbtnDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDobActionPerformed
        MovieLang = "Doblada";
    }//GEN-LAST:event_rbtnDobActionPerformed

    private void btnMoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoringActionPerformed
        MovieTime = "Mañana";
    }//GEN-LAST:event_btnMoringActionPerformed

    private void btnAfternoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfternoonActionPerformed
        MovieTime = "Tarde";
    }//GEN-LAST:event_btnAfternoonActionPerformed

    private void btnNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNightActionPerformed
        MovieTime = "Noche";
    }//GEN-LAST:event_btnNightActionPerformed

    private void btnSanPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPActionPerformed
        Location = "San Pedro";
    }//GEN-LAST:event_btnSanPActionPerformed

    private void btnMEscazuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEscazuActionPerformed
        Location = "Multiplaza Escazu";
    }//GEN-LAST:event_btnMEscazuActionPerformed

    private void btnPMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMayorActionPerformed
        Location = "Plaza Mayor";
    }//GEN-LAST:event_btnPMayorActionPerformed

    private void btnPFloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPFloresActionPerformed
        Location = "Paseo de las Flores";
    }//GEN-LAST:event_btnPFloresActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn2D;
    private javax.swing.JRadioButton btn3D;
    private javax.swing.JRadioButton btnAfternoon;
    private javax.swing.JButton btnContinueSelectMovie;
    private javax.swing.JButton btnExitSelectMovie;
    private javax.swing.JRadioButton btnMEscazu;
    private javax.swing.JRadioButton btnMoring;
    private javax.swing.JRadioButton btnNight;
    private javax.swing.JRadioButton btnPFlores;
    private javax.swing.JRadioButton btnPMayor;
    private javax.swing.JRadioButton btnSanP;
    private javax.swing.JRadioButton btnVIP;
    private javax.swing.ButtonGroup buttonGroupMovieType;
    private javax.swing.ButtonGroup buttonGroupTime;
    private javax.swing.JComboBox<String> cmbMovies;
    private javax.swing.ButtonGroup groupMovieLang;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMoviePic;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSelectMovie;
    public static javax.swing.JLabel lblUserBill;
    private javax.swing.JLabel lblWallpaperMovies;
    private javax.swing.JRadioButton rbtnDob;
    private javax.swing.JRadioButton rbtnSub;
    private javax.swing.JTextField txtMovieT;
    private javax.swing.JTextPane txtpSinopsis;
    // End of variables declaration//GEN-END:variables

}
